// array que contiene los datos de los productos
export const datos = [
  {
    id: 0,
    name: "Set para cocina",
    price: 1250,
    stock: 10,
    img: "img (1).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 1,
    name: "Mate Rosa",
    price: 790,
    stock: 9,
    img: "img (2).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 2,
    name: "Set de vasos X 3",
    price: 1250,
    stock: 1,
    img: "img (3).jpg",
    category: "cocina",
    offer: "true",
  },
  {
    id: 3,
    name: "Botellas BPA",
    price: 580,
    stock: 5,
    img: "img (4).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 4,
    name: "Super vaso tropical",
    price: 1120,
    stock: 1,
    img: "img (5).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 5,
    name: "Set Jarra + Vasos",
    price: 1020,
    stock: 1,
    img: "img (6).jpg",
    category: "cocina",
    offer: "true",
  },
  {
    id: 6,
    name: "Vaso cervecero",
    price: 530,
    stock: 19,
    img: "img (7).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 7,
    name: "Batidor manual",
    price: 760,
    stock: 18,
    img: "img (8).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 8,
    name: "Vaso térmico con bombilla",
    price: 280,
    stock: 0,
    img: "img (9).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 9,
    name: "Set para mates",
    price: 1030,
    stock: 6,
    img: "img (10).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 10,
    name: "Set lonchera",
    price: 1490,
    stock: 14,
    img: "img (11).jpg",
    category: "cocina",
    offer: "true",
  },
  {
    id: 11,
    name: "Vaso térmico",
    price: 890,
    stock: 4,
    img: "img (12).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 12,
    name: "Termo",
    price: 450,
    stock: 18,
    img: "img (13).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 13,
    name: "Set de mates",
    price: 1450,
    stock: 15,
    img: "img (14).jpg",
    category: "cocina",
    offer: "true",
  },
  {
    id: 14,
    name: "Vasos de playa",
    price: 1240,
    stock: 1,
    img: "img (15).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 15,
    name: "Set Mates ",
    price: 510,
    stock: 15,
    img: "img (16).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 16,
    name: "Vasos Térmicos 600ml",
    price: 700,
    stock: 11,
    img: "img (17).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 17,
    name: "Vaso tipo helado",
    price: 1360,
    stock: 13,
    img: "img (18).jpg",
    category: "cocina",
    offer: "true",
  },
  {
    id: 18,
    name: "Mate Autocebante",
    price: 420,
    stock: 1,
    img: "img (19).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 19,
    name: "Taza para niños",
    price: 720,
    stock: 14,
    img: "img (20).jpg",
    category: "cocina",
    offer: "true",
  },
  {
    id: 20,
    name: "Vaso con bombilla",
    price: 760,
    stock: 15,
    img: "img (21).jpg",
    category: "cocina",
    offer: "false",
  },
  {
    id: 21,
    name: "Soporte para jabón",
    price: 1200,
    stock: 6,
    img: "img (1).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 22,
    name: "Soporte para baño",
    price: 220,
    stock: 7,
    img: "img (2).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 23,
    name: "Soporte para baño",
    price: 800,
    stock: 9,
    img: "img (3).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 24,
    name: "Porta Cepillos",
    price: 1200,
    stock: 2,
    img: "img (4).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 25,
    name: "Dispenser jabón liquido",
    price: 810,
    stock: 16,
    img: "img (5).jpg",
    category: "banio",
    offer: "true",
  },
  {
    id: 26,
    name: "Porta cepillos",
    price: 580,
    stock: 0,
    img: "img (6).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 27,
    name: "Porta objetos",
    price: 860,
    stock: 0,
    img: "img (7).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 28,
    name: "Jabonera",
    price: 1340,
    stock: 19,
    img: "img (8).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 29,
    name: "Dispenser jabón líquido",
    price: 240,
    stock: 6,
    img: "img (9).jpg",
    category: "banio",
    offer: "true",
  },
  {
    id: 30,
    name: "Porta cepillos",
    price: 760,
    stock: 10,
    img: "img (10).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 31,
    name: "Porta objetos",
    price: 1180,
    stock: 4,
    img: "img (11).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 32,
    name: "jabonera",
    price: 370,
    stock: 3,
    img: "img (12).jpg",
    category: "banio",
    offer: "false",
  },
  {
    id: 33,
    name: "Mini maseteros de pvc",
    price: 750,
    stock: 13,
    img: "img (1).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 34,
    name: "Cuadro vintage",
    price: 1470,
    stock: 19,
    img: "img (2).jpg",
    category: "decoracion",
    offer: "true",
  },
  {
    id: 35,
    name: "Atrapasueños",
    price: 1090,
    stock: 7,
    img: "img (3).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 36,
    name: "Guirnaldas",
    price: 270,
    stock: 3,
    img: "img (4).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 37,
    name: "Colgante adorno",
    price: 230,
    stock: 6,
    img: "img (5).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 38,
    name: "Atrapasueño con plumas",
    price: 1140,
    stock: 9,
    img: "img (6).jpg",
    category: "decoracion",
    offer: "true",
  },
  {
    id: 39,
    name: "Mini macetero",
    price: 1020,
    stock: 18,
    img: "img (7).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 40,
    name: "Colgante LOVE",
    price: 440,
    stock: 10,
    img: "img (8).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 41,
    name: "Recipiente pintura",
    price: 550,
    stock: 9,
    img: "img (9).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 42,
    name: "mini Adorno macetero",
    price: 1380,
    stock: 15,
    img: "img (10).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 43,
    name: "Mini maceteros tipo buho",
    price: 670,
    stock: 11,
    img: "img (11).jpg",
    category: "decoracion",
    offer: "true",
  },
  {
    id: 44,
    name: "mini macetero tipo cactus",
    price: 1240,
    stock: 11,
    img: "img (12).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 45,
    name: "Soporte para toallas",
    price: 670,
    stock: 16,
    img: "img (13).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 46,
    name: "Adorno HOME",
    price: 190,
    stock: 10,
    img: "img (14).jpg",
    category: "decoracion",
    offer: "false",
  },
  {
    id: 47,
    name: "Atrapasueños multicolor",
    price: 1440,
    stock: 17,
    img: "img (15).jpg",
    category: "decoracion",
    offer: "true",
  },
  {
    id: 48,
    name: "Cuadro 10cm X 15cm",
    price: 1440,
    stock: 5,
    img: "img (16).jpg",
    category: "decoracion",
    offer: "false",
  },

  {
    id: 49,
    name: "sonajero",
    price: 1280,
    stock: 15,
    img: "img (1).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 50,
    name: "Sonajero",
    price: 810,
    stock: 1,
    img: "img (2).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 51,
    name: "Juguete para bañera",
    price: 900,
    stock: 6,
    img: "img (3).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 52,
    name: "Porta-Vasos inflable",
    price: 330,
    stock: 14,
    img: "img (4).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 53,
    name: "Porta-Vasos inflable",
    price: 470,
    stock: 5,
    img: "img (5).jpg",
    category: "juguetes",
    offer: "true",
  },
  {
    id: 54,
    name: "Pájaros a cuerda",
    price: 250,
    stock: 5,
    img: "img (6).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 55,
    name: "Serpiente de goma",
    price: 400,
    stock: 15,
    img: "img (7).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 56,
    name: "Lagarto de goma",
    price: 1210,
    stock: 14,
    img: "img (8).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 57,
    name: "Dino-Cartuchera",
    price: 420,
    stock: 7,
    img: "img (9).jpg",
    category: "juguetes",
    offer: "true",
  },
  {
    id: 58,
    name: "Taza tipo gato",
    price: 1050,
    stock: 10,
    img: "img (10).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 59,
    name: "Mini unicornio",
    price: 200,
    stock: 19,
    img: "img (11).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 60,
    name: "Helado de gatito",
    price: 1200,
    stock: 0,
    img: "img (12).jpg",
    category: "juguetes",
    offer: "true",
  },
  {
    id: 61,
    name: "Autito espacial",
    price: 1360,
    stock: 15,
    img: "img (13).jpg",
    category: "juguetes",
    offer: "true",
  },
  {
    id: 62,
    name: "Autito monster",
    price: 1120,
    stock: 1,
    img: "img (14).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 63,
    name: "Pollitos",
    price: 1130,
    stock: 14,
    img: "img (15).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 64,
    name: "Resortes emojis",
    price: 1260,
    stock: 0,
    img: "img (16).jpg",
    category: "juguetes",
    offer: "true",
  },
  {
    id: 65,
    name: "Resortes",
    price: 1330,
    stock: 2,
    img: "img (17).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 66,
    name: "Autito carrera RED",
    price: 490,
    stock: 9,
    img: "img (18).jpg",
    category: "juguetes",
    offer: "false",
  },
  {
    id: 67,
    name: "Cocodrilo bebé",
    price: 880,
    stock: 15,
    img: "img (19).jpg",
    category: "juguetes",
    offer: "true",
  },
  {
    id: 68,
    name: "Latas contenedoras",
    price: 1200,
    stock: 12,
    img: "img (1).jpg",
    category: "libreria",
    offer: "false",
  },
  {
    id: 69,
    name: "Latas redondas",
    price: 1090,
    stock: 3,
    img: "img (2).jpg",
    category: "libreria",
    offer: "false",
  },
  {
    id: 70,
    name: "Mini broches",
    price: 330,
    stock: 1,
    img: "img (3).jpg",
    category: "libreria",
    offer: "false",
  },
  {
    id: 71,
    name: "Cuadernos para regalos",
    price: 160,
    stock: 14,
    img: "img (4).jpg",
    category: "libreria",
    offer: "true",
  },
  {
    id: 72,
    name: "Cuaderno con candado",
    price: 1050,
    stock: 9,
    img: "img (5).jpg",
    category: "libreria",
    offer: "false",
  },
  {
    id: 73,
    name: "Mini agendas",
    price: 1130,
    stock: 14,
    img: "img (6).jpg",
    category: "libreria",
    offer: "false",
  },
  {
    id: 74,
    name: "Cuadernos tapa blanda",
    price: 570,
    stock: 3,
    img: "img (7).jpg",
    category: "libreria",
    offer: "false",
  }
];
